### ISSUE TITLE
System.DivideByZeroException in Indexer.cs : 658

### ISSUE THREAD

**Issue by teub** [jchristn/IndexEngine#1]
Hello,

I think there's a bug here:
Indexer.cs:658
decimal msPerTerm = Convert.ToDecimal((msTotal / termsRecorded).ToString("F"));

termsRecorded can be 0 and this leads to an exception being thrown. I guess documents should be indexed no matter what their content is, so this probably needs to be safe-guarded.

**Comment by jchristn** [comment]
Oooh, thanks for pointing this out, I'll take a look and update!

**Comment by jchristn** [comment]
Hi @teub thank you so much for pointing these out.  As I mentioned I have a broader refactor planned for this package, so I hope you can excuse the 'quick fix' on both of these issues (I'm sure there are more out there).  I plan to do a larger refactor on this package soon.  

For now, please let me know if the following meet your needs.  I'll leave both issues open to you to close if they are resolved.

NuGet v1.0.10: https://www.nuget.org/packages/IndexEngine/1.0.10
Commit: https://github.com/jchristn/IndexEngine/commit/97c77cd838c6d90ecd2ab0f7bf6a285e447f5758

Thanks again for filing these to make this package better.  I really appreciate it.  

Cheers, Joel
