### ISSUE TITLE
IsHandleIndexed doesn't work properly

### ISSUE THREAD

**Issue by teub** [jchristn/IndexEngine#2]
in IsHandledIndex code: 
`string query = "SELECT guid FROM docs WHERE handle = '" + DatabaseWrapper.SanitizeString(handle.ToLower()) + "'";`
=> the handle is lowercased

But when the document is actually registered, it's not:

```
               string query =
                    "INSERT INTO docs " +
                    "(title, description, handle, source, added_by, guid, added) " +
                    "VALUES " +
                    "(" +
                    "'" + DatabaseWrapper.SanitizeString(doc.Title) + "'," +
                    "'" + DatabaseWrapper.SanitizeString(doc.Description) + "'," +
                    "'" + DatabaseWrapper.SanitizeString(doc.Handle) + "'," +
                    "'" + DatabaseWrapper.SanitizeString(doc.Source) + "'," +
                    "'" + DatabaseWrapper.SanitizeString(doc.AddedBy) + "'," +
                    "'" + DatabaseWrapper.SanitizeString(doc.ReferenceGuid) + "'," +
                    "'" + doc.Added.ToString("MM/dd/yyyy HH:mm:ss") + "'" +
                    ")";
```

Therefore, the current code doesn't work for any handle that is not lowercased already.

As a fix, either the ToLower() call should be removed in IsHandledIndexed, or it should be added in the Create-New-Document-Entry section

**Comment by jchristn** [comment]
Good catch.  I can fix this easily by doing ```COLLATE NOCASE``` on the table definition, forcing all string comparisons to be case insensitive.  I have a broader project to modernize this one and leverage another one of my packages for database management, but I'll add this fix in with the other one you just filed, and do that before the broader project.  Thanks!

**Comment by jchristn** [comment]
Hi @teub thank you so much for pointing these out.  As I mentioned I have a broader refactor planned for this package, so I hope you can excuse the 'quick fix' on both of these issues (I'm sure there are more out there).  I plan to do a larger refactor on this package soon.  

For now, please let me know if the following meet your needs.  I'll leave both issues open to you to close if they are resolved.

NuGet v1.0.10: https://www.nuget.org/packages/IndexEngine/1.0.10
Commit: https://github.com/jchristn/IndexEngine/commit/97c77cd838c6d90ecd2ab0f7bf6a285e447f5758

Thanks again for filing these to make this package better.  I really appreciate it.  

Cheers, Joel

**Comment by teub** [comment]
I pulled the commit, and the fix for the casing doesn't seem to work. I tried recreating the .db file and the IsHandleIndexed query doesn't return documents if their handle contain upper case characters. I'll put back my local patch that Lowers the handle in the document insert code (*unless I made some mistake in my tests, but I can't see which one right now)

**Comment by teub** [comment]
Nevermind! I think the problem is on my side this time :)

**Comment by jchristn** [comment]
Awesome, thanks again @teub 

Have a great day!

**Comment by teub** [comment]
For the record, I couldn't find my documents with "IsHandleIndexed" because they were empty and this statement:
`                if (terms == null || terms.Count < 1)
                {
                    Log("ProcessSubmittedDocument no tags submitted or no terms found");
                    return;
                }`
prevents them from being added to the index.

I think they should be added even if empty, but that's a design decision you could disagree with.

**Comment by jchristn** [comment]
Point taken and I agree with you.  I'll make this change.  Give me a few moments!

**Comment by jchristn** [comment]
Hi @teub - please confirm this fixes and close if life is good!

NuGet v1.0.11: https://www.nuget.org/packages/IndexEngine/1.0.11
Commit: https://github.com/jchristn/IndexEngine/commit/b7df868640a82d3f3ff06e7f1581dc35cea61d44

**Comment by jchristn** [comment]
Hold tight on that, there's an issue with 100% empty, zero-byte files that I didn't consider.  Fixing now.

**Comment by jchristn** [comment]
Hi @teub 

Let's try this one.  Ran it through a few tests and I feel like this should do it.

NuGet: https://www.nuget.org/packages/IndexEngine/1.0.12
Commit: https://github.com/jchristn/IndexEngine/commit/8379d243a6072192a6ef90ed0929f0a8c21b9cb7

**Comment by teub** [comment]
it seems to work as intended, but I believe you forgot to remove a log line in Indexer.cs:406:

"Console.WriteLine(doc.ToString());"

**Comment by jchristn** [comment]
LOL.  I did indeed.  Fixing this now, and re-releasing

**Comment by jchristn** [comment]
Alright, this should do it.  Cheers!

NuGet: https://www.nuget.org/packages/IndexEngine/1.0.12.1
Commit: https://github.com/jchristn/IndexEngine/commit/cc9ee79670143ee9938ef2830d9babae35fe8256
